version: '3.4'

services:
  bingus-next:
    build: ./bingus-next
    image: bingus-next
    ports:
      - "3000:3000"
    container_name: bingus-next
    depends_on:
      - mongo
    
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: bullet

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: bullet
      ME_CONFIG_MONGODB_URL: mongodb://root:bullet@mongo:27017/
